# Generated by Django 4.2.23 on 2025-08-05 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0004_rename_avilable_days_hall_available_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musical_Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('band_members', models.CharField(max_length=250)),
                ('available_days', models.CharField(max_length=200)),
                ('set_hour', models.DateField()),
                ('price', models.PositiveBigIntegerField()),
                ('comment', models.TextField(default='no comment')),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall')),
            ],
            options={
                'verbose_name_plural': 'Musical Bands',
            },
        ),
    ]
