# Generated by Django 5.2.5 on 2025-08-19 15:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_alter_basic_packges_options_and_more'),
        ('musical_band', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musical_band',
            options={'verbose_name': 'Musical Band', 'verbose_name_plural': 'Musical Bands'},
        ),
        migrations.AlterModelOptions(
            name='usermusical_band',
            options={'verbose_name': 'User Musical Band', 'verbose_name_plural': 'User Musical Bands'},
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='available_day',
            field=models.DateField(blank=True, null=True, verbose_name='Available Day'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='band_members',
            field=models.CharField(max_length=250, verbose_name='Band Members'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='comment',
            field=models.TextField(default='No comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Band Name'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rate (1-5)'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='set_hour',
            field=models.TimeField(verbose_name='Set Hour'),
        ),
        migrations.AlterField(
            model_name='musical_band',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='usermusical_band',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Contact Info'),
        ),
        migrations.AlterField(
            model_name='usermusical_band',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='usermusical_band',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='usermusical_band',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
