# Generated by Django 4.2.23 on 2025-08-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_band', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musical_band',
            name='available_days',
        ),
        migrations.AddField(
            model_name='musical_band',
            name='available_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
