# Generated by Django 4.2.23 on 2025-08-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dj_image', models.ImageField(upload_to='dj_images')),
                ('avilable_days', models.CharField(max_length=50)),
                ('set_hour', models.DateTimeField()),
                ('price', models.PositiveBigIntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall')),
            ],
            options={
                'verbose_name': 'DJ',
                'verbose_name_plural': 'DJs',
                'db_table': 'dj',
                'ordering': ['-set_hour'],
                'unique_together': {('dj_name', 'hall')},
            },
        ),
    ]
