# Generated by Django 5.2.5 on 2025-08-17 14:55

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dj_image', models.ImageField(upload_to='dj_images')),
                ('available_day', models.DateField(blank=True, null=True)),
                ('set_hour', models.TimeField()),
                ('price', models.PositiveBigIntegerField()),
                ('type_event', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('graduation', 'Graduation'), ('other', 'Other')], max_length=100)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('comment', models.TextField(default='No comment')),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall')),
            ],
            options={
                'verbose_name_plural': 'DJs',
            },
        ),
    ]
