# Generated by Django 4.2.23 on 2025-08-05 14:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dj',
            options={},
        ),
        migrations.RenameField(
            model_name='dj',
            old_name='avilable_days',
            new_name='available_days',
        ),
        migrations.AlterUniqueTogether(
            name='dj',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dj',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
        migrations.AddField(
            model_name='dj',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dj',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='dj',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='dj',
            name='type_event',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dj',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='dj',
            table=None,
        ),
    ]
