# Generated by Django 5.2.5 on 2025-08-19 15:08

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0001_initial'),
        ('hall', '0002_alter_basic_packges_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdj',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='dj',
            name='available_day',
            field=models.DateField(blank=True, null=True, verbose_name='Available Day'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='comment',
            field=models.TextField(default='No comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='dj_image',
            field=models.ImageField(upload_to='dj_images', verbose_name='DJ Image'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='dj_name',
            field=models.CharField(max_length=50, verbose_name='DJ Name'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='set_hour',
            field=models.TimeField(verbose_name='Set Hour'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='type_event',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('graduation', 'Graduation'), ('other', 'Other')], max_length=100, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='dj',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
