# Generated by Django 4.2.23 on 2025-08-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0002_alter_dj_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dj',
            options={'verbose_name_plural': 'DJs'},
        ),
    ]
