# Generated by Django 4.2.23 on 2025-08-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0003_alter_dj_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dj',
            name='available_days',
        ),
        migrations.AddField(
            model_name='dj',
            name='available_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dj',
            name='set_hour',
            field=models.TimeField(),
        ),
    ]
