# Generated by Django 4.2.23 on 2025-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0004_remove_dj_available_days_dj_available_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dj',
            name='type_event',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('graduation', 'Graduation'), ('other', 'Other')], max_length=100),
        ),
    ]
