# Generated by Django 4.2.23 on 2025-08-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0004_rename_avilable_days_hall_available_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('light_type', models.CharField(choices=[('LED', 'LED'), ('Laser', 'Laser'), ('Spotlight', 'Spotlight'), ('Strobe', 'Strobe')], max_length=50)),
                ('power_watts', models.PositiveIntegerField()),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('price_per_event', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='light_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('Red', '#FF0000'), ('Blue', '#0000FF'), ('Green', '#00FF00'), ('Yellow', '#FFFF00'), ('Orange', '#FFA500'), ('Purple', '#800080'), ('White', '#FFFFFF')], max_length=7)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lights', to='hall.hall')),
            ],
        ),
    ]
