# Generated by Django 4.2.23 on 2025-08-09 16:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_remove_hall_available_days_hall_available_day'),
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='light',
            old_name='name',
            new_name='event_type',
        ),
        migrations.RemoveField(
            model_name='light',
            name='color',
        ),
        migrations.RemoveField(
            model_name='light',
            name='description',
        ),
        migrations.RemoveField(
            model_name='light',
            name='image',
        ),
        migrations.RemoveField(
            model_name='light',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='light',
            name='light_type',
        ),
        migrations.RemoveField(
            model_name='light',
            name='power_watts',
        ),
        migrations.RemoveField(
            model_name='light',
            name='price_per_event',
        ),
        migrations.RemoveField(
            model_name='light',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='light',
            name='available_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light',
            name='comments',
            field=models.TextField(default='No comments', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='light',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='light',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='light',
            name='set_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='light',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='light',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
        ),
    ]
