# Generated by Django 5.2.5 on 2025-08-19 15:08

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_alter_basic_packges_options_and_more'),
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='light',
            options={'verbose_name': 'Light', 'verbose_name_plural': 'Lights'},
        ),
        migrations.AlterModelOptions(
            name='userlight',
            options={'verbose_name': 'User Light', 'verbose_name_plural': 'User Lights'},
        ),
        migrations.AlterField(
            model_name='light',
            name='available_day',
            field=models.DateField(blank=True, null=True, verbose_name='Available Day'),
        ),
        migrations.AlterField(
            model_name='light',
            name='comments',
            field=models.TextField(max_length=500, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='light',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='light',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='light',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('company_party', 'Company Party'), ('private_party', 'Private Party'), ('other', 'Other')], max_length=100, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='light',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='light',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rate (1-5)'),
        ),
        migrations.AlterField(
            model_name='light',
            name='set_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='Set Hour'),
        ),
        migrations.AlterField(
            model_name='light',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Contact Info'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
