# Generated by Django 4.2.23 on 2025-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0002_rename_name_light_event_type_remove_light_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
