# Generated by Django 5.2.5 on 2025-08-17 14:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DJ', '0001_initial'),
        ('hall', '0001_initial'),
        ('lights', '0001_initial'),
        ('musical_band', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('dj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DJ.dj')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall')),
                ('light', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lights.light')),
                ('musical_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musical_band.musical_band')),
                ('user_dj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DJ.userdj')),
                ('user_light', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lights.userlight')),
                ('user_musical_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musical_band.usermusical_band')),
            ],
        ),
        migrations.CreateModel(
            name='UserDJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dj_image', models.ImageField(blank=True, null=True, upload_to='user_dj_images')),
                ('available_day', models.DateField(blank=True, null=True)),
                ('set_hour', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_event', models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('graduation', 'Graduation'), ('other', 'Other')], max_length=50)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('comment', models.TextField(blank=True, default='No comment')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_djs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('available_day', models.DateField(blank=True, null=True)),
                ('set_hour', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, default='no comment')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_lights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMusicalBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('band_members', models.CharField(blank=True, max_length=250)),
                ('available_day', models.DateField(blank=True, null=True)),
                ('set_hour', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, default='no comment')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
