# Generated by Django 5.2.5 on 2025-08-19 15:08

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJ', '0002_alter_userdj_options_alter_dj_available_day_and_more'),
        ('cart', '0002_alter_userdj_user'),
        ('hall', '0002_alter_basic_packges_options_and_more'),
        ('lights', '0002_alter_light_options_alter_userlight_options_and_more'),
        ('musical_band', '0002_alter_musical_band_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='dj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DJ.dj', verbose_name='DJ'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lights.light', verbose_name='Light'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='musical_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musical_band.musical_band', verbose_name='Musical Band'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user_dj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DJ.userdj', verbose_name='User DJ'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user_light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lights.userlight', verbose_name='User Light'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user_musical_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musical_band.usermusical_band', verbose_name='User Musical Band'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='available_day',
            field=models.DateField(blank=True, null=True, verbose_name='Available Day'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='comment',
            field=models.TextField(blank=True, default='No comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='dj_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_dj_images', verbose_name='DJ Image'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='dj_name',
            field=models.CharField(max_length=100, verbose_name='DJ Name'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='set_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='Set Hour'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='type_event',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('graduation', 'Graduation'), ('other', 'Other')], max_length=50, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userdj',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='available_day',
            field=models.DateField(blank=True, null=True, verbose_name='Available Day'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='comment',
            field=models.TextField(blank=True, default='No comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Light Name'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='set_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='Set Hour'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userlight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_lights', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='available_day',
            field=models.DateField(blank=True, null=True, verbose_name='Available Day'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='band_members',
            field=models.CharField(blank=True, max_length=250, verbose_name='Band Members'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='comment',
            field=models.TextField(blank=True, default='No comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall', verbose_name='Hall'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Band Name'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='set_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='Set Hour'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='usermusicalband',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bands', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
