# Generated by Django 4.2.23 on 2025-08-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_delete_booking'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('hall', 'date', 'start_time', 'end_time')},
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
