# Generated by Django 5.2.5 on 2025-08-19 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basic_packges',
            options={'verbose_name': 'Basic Package', 'verbose_name_plural': 'Basic Packages'},
        ),
        migrations.AlterModelOptions(
            name='extra_packges',
            options={'verbose_name': 'Extra Package', 'verbose_name_plural': 'Extra Packages'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Hall', 'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='userhall',
            options={'verbose_name': 'User Hall', 'verbose_name_plural': 'User Halls'},
        ),
        migrations.AlterField(
            model_name='basic_packges',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='basic_packges',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='basic_packges',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='basic_packges',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='basic_packges',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='extra_packges',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='extra_packges',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='extra_packges',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='extra_packges',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='extra_packges',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='available_day',
            field=models.DateField(blank=True, null=True, verbose_name='Available Day'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='basic_Packges',
            field=models.ManyToManyField(blank=True, related_name='basic_Packges', to='hall.basic_packges', verbose_name='Basic Packages'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='comments',
            field=models.TextField(verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='extra_Packges',
            field=models.ManyToManyField(blank=True, related_name='extra_Packges', to='hall.extra_packges', verbose_name='Extra Packages'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Hall Name'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rate (1-5)'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='set_the_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userhall',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Contact Info'),
        ),
        migrations.AlterField(
            model_name='userhall',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userhall',
            name='name',
            field=models.CharField(max_length=100, verbose_name='User Hall Name'),
        ),
        migrations.AlterField(
            model_name='userhall',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
