# Generated by Django 4.2.23 on 2025-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='basic_Packges',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='extra_Packges',
        ),
        migrations.AddField(
            model_name='hall',
            name='basic_Packges',
            field=models.ManyToManyField(blank=True, related_name='basic_Packges', to='hall.basic_packges'),
        ),
        migrations.AddField(
            model_name='hall',
            name='extra_Packges',
            field=models.ManyToManyField(blank=True, related_name='extra_Packges', to='hall.extra_packges'),
        ),
    ]
