# Generated by Django 4.2.23 on 2025-08-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_remove_hall_basic_packges_remove_hall_extra_packges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='avilable_days',
            new_name='available_days',
        ),
    ]
