# Generated by Django 4.2.23 on 2025-08-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_rename_avilable_days_hall_available_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
